### ISSUE TITLE
[WebHook] Can I get the payment method somewhere ?

### ISSUE THREAD

**Issue by laurent-xu** [ProcessOut/documentation#6]
Is the processor field in the webhook json the payment method used by the customer ?
If it is, it would be great to replace in the example "ProcessOut" by "Paypal" or "Stripe" to be more explicit.
Otherwise, It may be a good idea to provide this information in the webhook.

**Comment by manuel-huez** [comment]
This field is in fact the name of the processor, lowercased. I'll replace it by PayPal to clarify it.
